module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:promise/recommended',
    'airbnb',
    'plugin:jest/recommended',
    'plugin:flowtype/recommended',
  ],
  plugins: [
    'react',
    'jsx-a11y',
    'import',
    'react-native',
    'flowtype',
    'flowtype-errors',
    'lodash-fp',
    'promise',
    'jest',
    'json',
  ],
  rules: {
    'class-methods-use-this': 1,
    'comma-dangle': ['error', 'always-multiline'],
    'flowtype-errors/show-errors': 2,
    'flowtype-errors/show-warnings': 1,
    'global-require': 2,
    'import/max-dependencies': 1,
    'import/newline-after-import': [1, { count: 2 }],
    'import/no-cycle': [2, { maxDepth: 5 }],
    'import/no-useless-path-segments': 2,
    'import/order': ['error', { 'newlines-between': 'always', 'groups': [['builtin', 'external'], ['parent', 'sibling', 'index']] }],
    'indent': ['error', 2, { VariableDeclarator: { var: 2, let: 2, const: 3 } }],
    'jsx-a11y/accessible-emoji': 0,
    'jsx-quotes': ['error', 'prefer-single'],
    'lodash-fp/use-fp': 2,
    'no-confusing-arrow': 0,
    'no-extra-parens': ['error', 'all', { ignoreJSX: 'all', enforceForArrowConditionals: false, nestedBinaryExpressions: false }],
    'no-nested-ternary': 0,
    'no-return-assign': 0,
    'no-underscore-dangle': 1,
    'no-unused-expressions': 0,
    'no-useless-computed-key': 2,
    'one-var': 0,
    'promise/catch-or-return': 1,
    'promise/no-native': 1,
    'quote-props': ['error', 'consistent-as-needed'],
    'react-native/no-color-literals': 0,
    'react-native/no-unused-styles': 2,
    'react-native/no-inline-styles': 1,
    'react-native/split-platform-components': 1,
    'react/boolean-prop-naming': ['error', { rule: '^(is|has)[A-Z]([A-Za-z0-9]?)+', propTypeNames: ['bool', 'mutuallyExclusiveTrueProps'] }],
    'react/jsx-filename-extension': 0,
    'react/prefer-stateless-function': ['error', { ignorePureComponents: true }],
    'react/prop-types': [2, { skipUndeclared: true }],
    'react/sort-comp': 0,
    'sort-vars': 2,
    'quotes': [
      'error',
      'single',
      { avoidEscape: true, allowTemplateLiterals: true },
    ],
    'no-mixed-operators': [
      'error',
      {
        groups: [
          ['+', '-', '*', '/', '%', '**'],
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: true,
      },
    ],
  },
  env: {
    'jest/globals': true,
  },
  globals: {
    fetch: true,
    __DEV__: true,
    __OFFLINE__: true,
    window: true,
  },
  settings: {
    'flowtype': {
      onlyFilesWithFlowAnnotation: true,
    },
    'import/resolver': {
      node: {
        extensions: [
          '.js',
          '.jsx',
          '.ios.js',
          '.android.js',
        ],
      },
    },
  },
};
